[project]
name = "sahibhav-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "manas-swain-001", email = "manas.swain247@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "langchain-core>=0.3.0",
    "langchain-groq>=0.2.0",
    "pydantic>=2.7.0",
    "python-dotenv>=1.0.0",
    "httpx>=0.27.0",
    "fastapi>=0.142.2",
    "uvicorn>=0.54.0",
]

[project.scripts]
sahibhav-ai = "sahibhav_ai:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"

[tool.pyright]
venvPath = "."
venv = ".venv"

